AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild Project Stack'
Parameters:
  Env:
    Description: 'Environment name'
    Type: String
    AllowedValues: ['staging', 'production']
    Default: 'staging'
  GitHubOwner:
    Type: String
    Description: 'GitHub repository owner'
  GitHubRepo:
    Type: String
    Description: 'GitHub repository name'
  GitHubToken:
    Type: String
    Description: 'GitHub personal access token'
    NoEcho: true
  GitHubBranch:
    Type: String
    Description: 'GitHub branch name'
    Default: 'main'
  BuildSpec:
    Type: String
    Description: 'S3 url'

Resources:

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: '*'
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:CreateRepository
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DeleteRepository
                  - ecr:TagResource
                  - ecr:UntagResource
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: '*'
                
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    #DeletionPolicy: Retain
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Ref GitHubToken
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "dash-build"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepo}.git"
        BuildSpec: !Ref BuildSpec
        Auth:
          Resource: !Ref CodeBuildSourceCredential
          Type: OAUTH
      SourceVersion: !Ref GitHubBranch
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub "^refs/heads/${GitHubBranch}$"
