AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository Stack'
Parameters:
  Env:
    Description: 'Environment name'
    Type: String
    AllowedValues: ['staging', 'production']
    Default: 'staging'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "dash-${Env}-repository"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only 2 untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryURI:
    Description: 'ECR Repository URI'
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryURI
  RepositoryName:
    Description: 'ECR Repository Name'
    Value: !Ref ECRRepository
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryName